export const UPLOAD_CONFIG = {
  MAX_FILE_SIZE_BYTES: 2 * 1024 * 1024 * 1024, // 2 GB
  CHUNK_SIZE_BYTES: 30 * 1024 * 1024, // 30 MB
  MAX_FETCH_RETRIES: 3,
};

export const LESSON_UPLOAD_STATUS = {
  IDLE: "IDLE",
  PREPARING: "PREPARING",
  UPLOADING: "UPLOADING",
  PAUSED: "PAUSED",
  PROCESSING: "PROCESSING",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  ERROR: "ERROR",
} as const;

export type LessonUploadStatus = keyof typeof LESSON_UPLOAD_STATUS; 